ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM balenalib/$BALENA_ARCH-alpine

RUN install_packages dbus

WORKDIR /usr/src/app

COPY entry.sh ./

COPY *.conf ./

COPY VERSION ./

ENTRYPOINT  ["sh","./entry.sh"]